[project]
name = "qmtdatatool"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "dotenv>=0.9.9",
    "numpy>=2.2.6",
    "openpyxl>=3.1.5",
    "pytz>=2025.2",
]
